import { z } from "zod";

export const healthCheckToolDefinition = {
  name: "health_check",
  title: "Health Check",
  description: "Returns a small structured heartbeat payload for monitoring.",
  inputSchema: {},
  outputSchema: {
    status: z.string(),
    timestamp: z
      .string()
      .describe("ISO-8601 timestamp generated by the server.")
  },
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false
  }
} as const;
