import { z } from "zod";

export const healthCheckToolOutputSchema = {
  status: z.literal("ok"),
  timestamp: z.string().describe("ISO-8601 timestamp generated by the server.")
} as const;

export const healthCheckToolOutputValidator = z.object(
  healthCheckToolOutputSchema
);

export const healthCheckToolDefinition = {
  name: "health_check",
  title: "Health Check",
  description: "Returns a small structured heartbeat payload for monitoring.",
  inputSchema: {},
  outputSchema: healthCheckToolOutputSchema,
  annotations: {
    readOnlyHint: true,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false
  }
} as const;
